apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels :
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: wordpress        
          env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: docker 
          securityContext:
            privileged: true 
          volumeMounts:
          - mountPath: /var/www/html
            name: volstorage 
      volumes:
      - name: volstorage
        hostPath:
          path: /root/kubernetes
          type: DirectoryOrCreate
  selector:
    matchLabels:
      type: frontend
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    type: frontend
  ports:
    - name: http
      port: 80
      nodePort : 30000
  type: NodePort

