apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: backend-app
    type: backend
spec:
  template:
    metadata:
      name: backend-pod
      labels :
        app: backend-app
        type: backend
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
          - containerPort: 3306        
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: docker
          - name: MYSQL_USER
            value: docker
          - name: MYSQL_PASSWORD
            value: docker
          - name: MYSQL_DATABASE
            value: wordpress 
          securityContext:
            privileged: true 
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: volstorage 
      volumes:
      - name: volstorage
        hostPath:
          path: /root/kubernetes2
          type: DirectoryOrCreate
  selector:
    matchLabels:
      type: backend
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  selector:
    type: backend
  ports:
    - name: mysql
      port: 3306
      nodePort : 30001
  type: NodePort

